Completely redesign the HR/Recruiter Dashboard (MentorDashboard.tsx or create a new RecruiterDashboard.tsx). Replace all instances of the word "Company" with "Recruiter" throughout the platform. The recruiter's navigation should have exactly 5 items: Home, Talent Search, College Connect, Active Drives, and Onboarding Tracker.
Home: A command centre showing: count of open positions with total applicants, a "New Matches" feed of student profiles that fit the recruiter's saved criteria, recent activity from students they've shortlisted, and quick action buttons — Post a Job, Search Talent, Start a Campus Drive.
Talent Search: Two search modes accessible via a toggle — "Find a Person" and "Find by Problem". In Find a Person mode, show filterable student cards with photo, name, college, course, graduation year, Innovation Score badge, top 3 skills, and latest project. Filters include: domain, college, graduation year, Innovation Score range, patent status, and availability (internship/full-time). In Find by Problem mode, show a text input where the recruiter types a problem statement, and the results show students whose projects match that domain/problem — with the matching project highlighted on the card.
Student Profile Page: When a recruiter opens a student profile, show it as a portfolio page — NOT a resume. Sections: Header (photo, name, college, Innovation Score, availability), Education, Projects (each project as a card with problem statement, domain, role, outcome, tech used, mentor, patent status), Skills (auto-derived from projects), Achievements (patents, competition wins, badges), Internship History, and Mentor Recommendations. Include a "Shortlist" button and a "Message" button.
College Connect: A searchable grid of institution cards showing NAAC grade, NIRF rank, IIC star rating, active students, and top project domains. Clicking a college shows their full profile. Each college card has a "Post Campus Drive" button and a "Request Partnership" button. Posting a drive lets the recruiter set eligibility criteria, openings count, and job description — this drive is then visible to eligible students at that college.
Active Drives: A table view of all posted drives showing: drive name, college, total applications, shortlisted, interviewed, offered, and current status. Clicking a drive opens a pipeline view of all applicants moving through stages (Applied → Shortlisted → Interviewed → Offered → Joined).
Onboarding Tracker: A board showing all hired/interned students in onboarding stages: Offer Sent → Offer Accepted → Documents Submitted → Joining Confirmed → Day 1 → 30-Day Check-in. Students stuck at a stage for more than 3 days are highlighted in amber/red. Each student card shows name, college, role, and a "Send Reminder" button.
Keep ProMove's existing visual style, sidebar structure, and color scheme throughout.
  Redesign the Student Dashboard (StudentDashboard.tsx) by integrating the existing course learning interface with ProMove's innovation journey. The layout should use a two-column structure: a wide main content area on the left and a sidebar of widgets on the right. Keep ProMove's existing branding and sidebar navigation.
Left sidebar navigation: Dashboard, My Courses, My Innovation Journey, My Portfolio, My Mentor, Opportunities, Leaderboard.
Main content area (top to bottom):
First, a personalised welcome banner with the student's name, a motivational line about their weekly goal progress, and a streak counter showing consecutive days active on the platform (displayed as a flame icon with a number, e.g. "🔥 7 day streak").
Second, an Active Course card — showing the current course name, module title, last visited timestamp, a progress bar with percentage, and a "Resume Learning" button. Style this exactly like the Wix screenshot reference provided — clean card with a course thumbnail on the left.
Third, an Innovation Journey Stepper — a horizontal step-by-step progress bar showing 6 stages: Idea, Problem Matched, Building, Patent, Launch, Marketplace. Completed stages are shown with a filled checkmark, the current stage is highlighted with the primary ProMove color, future stages are greyed out. Each stage is clickable and links to its corresponding tool page.
Fourth, an Active Project card — showing project title, domain tag, team member avatars, overall progress percentage, assigned mentor name, next milestone title and due date, and a "Continue Working" button.
Fifth, a "Suggested for You" section with 3 course cards — same layout as the Wix screenshot. Each card shows a thumbnail, duration, difficulty badge, course title, short description, and a "View Course" button.
Right sidebar widgets (top to bottom):
First, an Innovation Score card — a large circular dial showing the student's score out of 1000. Below the dial, show the last 2–3 score changes as a feed (e.g. "+15 pts — Patent filed", "+10 pts — Mentor session completed"). Below that, one actionable tip: "Complete your product demo to earn +25 pts."
Second, an Upcoming Deadlines widget — list of 3–4 items each with title, course/project name, and a color-coded due date badge (red = due tomorrow, amber = this week, green = later).
Third, a Calendar widget — a monthly mini calendar with dates that have events highlighted with dots. Clicking a date shows a tooltip with what's scheduled.
Fourth, a Notifications widget — showing recent alerts like "An investor viewed your profile", "Mentor left feedback on your project", "New internship opportunity matched", with timestamps. A "View all" link at the bottom.
Additional pages:
My Portfolio page: Show the student a preview of their own public-facing profile exactly as investors and recruiters see it — sections for About, Education, Projects (as cards), Skills, Achievements, and Certificates. Include an "Edit Portfolio" button and a "Share Portfolio" button that copies a shareable link.
My Mentor page: Show assigned mentor's photo, name, company, and expertise. A session history list with dates and notes. An upcoming session card with a "Schedule Session" button. A message thread below.
Opportunities page: Two tabs — Internships & Jobs (filtered to the student's skills and domain) and Events & Competitions (showing hackathons, innovation drives, and campus recruitment events at their college).
Leaderboard page: Innovation Score rankings with three tabs — My College, My City, All India. Each row shows rank, student avatar, name, college, and score. The logged-in student's row is always highlighted regardless of rank.
The overall feel should be motivating and gamified — like a mix of Duolingo's habit-building and LinkedIn's professional portfolio — while staying consistent with ProMove's existing visual style.