import { Types } from 'mongoose';
import { notificationQueue } from '../../config/bullmq';
import { ApiError } from '../../utils/ApiError';
import { ActivityLogService } from '../activityLog/activityLog.service';
import { Bid } from '../bidding/bidding.model';
import { Startup } from '../startup/startup.model';
import { User } from '../user/user.model';
import { Agreement } from './agreement.model';
import type { AgreementView, IAgreement, IAgreementTermsSnapshot } from './agreement.types';

const formatINR = (value: number) =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(value);

const generateAgreementNumber = () => {
  const date = new Date();
  const yy = String(date.getUTCFullYear()).slice(-2);
  const mm = String(date.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(date.getUTCDate()).padStart(2, '0');
  const random = Math.random().toString(36).slice(2, 8).toUpperCase();
  return `PMV-AGR-${yy}${mm}${dd}-${random}`;
};

const buildAgreementBody = (terms: IAgreementTermsSnapshot, agreementNumber: string): string => {
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  return `VIRTUAL INVESTMENT AGREEMENT
Agreement No: ${agreementNumber}
Date: ${today}

PARTIES

Founder: ${terms.founderName}
Investor: ${terms.investorName}
Startup: ${terms.startupName}

TERMS

1. The Investor commits a virtual investment of ${formatINR(terms.amount)}
   in exchange for ${terms.equity}% equity in ${terms.startupName}.
2. The Investor will participate as a ${terms.investorRole}.
3. Investment type: ${terms.bidType === 'sole' ? 'Sole Investor (lead)' : 'Penny Investor (portfolio)'}.

NATURE OF AGREEMENT

This is a virtual, non-binding simulation generated by the ProMove platform for
educational and platform-internal record-keeping purposes only. It does not
create real legal obligations and does not represent a transfer of actual money
or securities. Any binding agreement requires separate offline execution.

ACKNOWLEDGEMENT

By accepting the underlying bid, both parties acknowledge the terms recorded
above as their final negotiated position within the ProMove simulation.`;
};

const serializeAgreement = (a: IAgreement): AgreementView => ({
  _id: String(a._id),
  bidId: String(a.bidId),
  startupId: String(a.startupId),
  investorId: String(a.investorId),
  founderId: String(a.founderId),
  dealId: a.dealId ? String(a.dealId) : undefined,
  agreementNumber: a.agreementNumber,
  status: a.status,
  terms: a.terms,
  bodyText: a.bodyText,
  acknowledgedByInvestorAt: a.acknowledgedByInvestorAt?.toISOString(),
  acknowledgedByFounderAt: a.acknowledgedByFounderAt?.toISOString(),
  voidedAt: a.voidedAt?.toISOString(),
  voidReason: a.voidReason,
  generatedAt: a.generatedAt.toISOString(),
  createdAt: a.createdAt.toISOString(),
  updatedAt: a.updatedAt.toISOString(),
});

export const generateAgreementForAcceptedBid = async (
  bidId: string,
): Promise<AgreementView | null> => {
  const existing = await Agreement.findOne({ bidId });
  if (existing) {
    return serializeAgreement(existing as unknown as IAgreement);
  }

  const bid = await Bid.findById(bidId).lean();
  if (!bid || bid.status !== 'accepted') return null;

  const [startup, investor, founder] = await Promise.all([
    Startup.findById(bid.startupId).select('name').lean(),
    User.findById(bid.investorId).select('displayName').lean(),
    User.findById(bid.founderId).select('displayName').lean(),
  ]);
  if (!startup || !investor || !founder) return null;

  const terms: IAgreementTermsSnapshot = {
    bidType: bid.bidType,
    amount: bid.finalAmount ?? bid.counterAmount ?? bid.proposedAmount,
    equity: bid.finalEquity ?? bid.counterEquity ?? bid.proposedEquity,
    investorRole: bid.investorRole ?? 'shareholder',
    startupName: startup.name,
    founderName: founder.displayName ?? 'Founder',
    investorName: investor.displayName ?? 'Investor',
  };

  const agreementNumber = generateAgreementNumber();
  const bodyText = buildAgreementBody(terms, agreementNumber);

  const created = await Agreement.create({
    bidId: new Types.ObjectId(String(bid._id)),
    startupId: bid.startupId,
    investorId: bid.investorId,
    founderId: bid.founderId,
    dealId: bid.dealId,
    agreementNumber,
    status: 'generated',
    terms,
    bodyText,
    generatedAt: new Date(),
  });

  await ActivityLogService.log({
    actorId: String(bid.founderId),
    action: 'BID_ACCEPTED',
    entityType: 'Agreement',
    entityId: String(created._id),
    metadata: {
      bidId,
      startupId: String(bid.startupId),
      agreementNumber,
    },
  });

  await Promise.all([
    notificationQueue.add('agreement-generated', {
      userId: String(bid.investorId),
      type: 'deal_interest',
      title: 'Virtual agreement generated',
      body: `Your agreement ${agreementNumber} for ${startup.name} is ready to review.`,
      link: `/agreements/${String(created._id)}`,
      metadata: {
        agreementId: String(created._id),
        bidId,
        startupId: String(bid.startupId),
      },
    }),
    notificationQueue.add('agreement-generated', {
      userId: String(bid.founderId),
      type: 'deal_interest',
      title: 'Virtual agreement generated',
      body: `Agreement ${agreementNumber} with ${investor.displayName ?? 'investor'} is ready.`,
      link: `/agreements/${String(created._id)}`,
      metadata: {
        agreementId: String(created._id),
        bidId,
        startupId: String(bid.startupId),
      },
    }),
  ]);

  return serializeAgreement(created as unknown as IAgreement);
};

export const getAgreement = async (
  userId: string,
  agreementId: string,
): Promise<AgreementView> => {
  const a = await Agreement.findById(agreementId);
  if (!a) throw new ApiError(404, 'AGREEMENT_NOT_FOUND', 'Agreement not found');
  const isParticipant =
    String(a.investorId) === userId || String(a.founderId) === userId;
  if (!isParticipant) {
    throw new ApiError(403, 'FORBIDDEN', 'You are not a party to this agreement');
  }
  return serializeAgreement(a as unknown as IAgreement);
};

export const getAgreementByBid = async (
  userId: string,
  bidId: string,
): Promise<AgreementView | null> => {
  const a = await Agreement.findOne({ bidId });
  if (!a) return null;
  const isParticipant =
    String(a.investorId) === userId || String(a.founderId) === userId;
  if (!isParticipant) {
    throw new ApiError(403, 'FORBIDDEN', 'You are not a party to this agreement');
  }
  return serializeAgreement(a as unknown as IAgreement);
};

export const listAgreementsForUser = async (userId: string): Promise<AgreementView[]> => {
  const list = await Agreement.find({
    $or: [{ investorId: userId }, { founderId: userId }],
  })
    .sort({ createdAt: -1 })
    .lean();
  return list.map((a) => serializeAgreement(a as unknown as IAgreement));
};

export const acknowledgeAgreement = async (
  userId: string,
  agreementId: string,
): Promise<AgreementView> => {
  const a = await Agreement.findById(agreementId);
  if (!a) throw new ApiError(404, 'AGREEMENT_NOT_FOUND', 'Agreement not found');
  const isInvestor = String(a.investorId) === userId;
  const isFounder = String(a.founderId) === userId;
  if (!isInvestor && !isFounder) {
    throw new ApiError(403, 'FORBIDDEN', 'You are not a party to this agreement');
  }

  const now = new Date();
  if (isInvestor && !a.acknowledgedByInvestorAt) a.acknowledgedByInvestorAt = now;
  if (isFounder && !a.acknowledgedByFounderAt) a.acknowledgedByFounderAt = now;

  if (a.acknowledgedByInvestorAt && a.acknowledgedByFounderAt) {
    a.status = 'acknowledged_by_both';
  } else if (a.acknowledgedByInvestorAt) {
    a.status = 'acknowledged_by_investor';
  } else if (a.acknowledgedByFounderAt) {
    a.status = 'acknowledged_by_founder';
  }

  await a.save();
  return serializeAgreement(a as unknown as IAgreement);
};
