import { Schema, model } from 'mongoose';
import { IStartup } from './startup.types';

const startupDocumentCategoryEnum = [
  'business_plan',
  'incorporation_certificate',
  'moa',
  'aoa',
  'llp_agreement',
  'partnership_deed',
  'founder_agreement',
  'company_pan',
  'tan_allotment',
  'gst_registration',
  'registered_office_proof',
  'office_noc_or_utility_bill',
  'startup_india_certificate',
  'trademark_certificate',
  'patent_proof',
  'bank_account_proof',
  'regulatory_license',
  'prototype_documentation',
  'technical_documentation',
  'drawings_diagrams',
  'design_plan_sketch',
  'prior_art_search',
] as const;

const startupSchema = new Schema<IStartup>(
  {
    founderIds: { type: [Schema.Types.ObjectId], required: true, default: [], index: true },
    teamMemberIds: { type: [Schema.Types.ObjectId], default: [] },
    projectId: { type: Schema.Types.ObjectId, default: undefined },
    name: { type: String, required: true, trim: true, default: '' },
    tagline: { type: String, required: true, trim: true, default: '' },
    category: { type: String, required: true, trim: true, default: '' },
    stage: {
      type: String,
      enum: ['Pre-Idea', 'Ideation', 'MVP', 'Pre-Launch', 'Launched'],
      default: 'Pre-Idea',
    },
    pitchDeckUrl: { type: String, default: undefined },
    pitchDeckName: { type: String, default: undefined },
    teamSize: { type: Number, default: 1 },
    fundingNeeded: { type: Number, default: undefined },
    activeProducts: { type: Number, default: 1 },
    businessProfile: {
      problemStatement: { type: String, trim: true, default: '' },
      solutionSummary: { type: String, trim: true, default: '' },
      targetCustomers: { type: String, trim: true, default: '' },
      marketAnalysis: { type: String, trim: true, default: '' },
      revenueModel: { type: String, trim: true, default: '' },
      goToMarketPlan: { type: String, trim: true, default: '' },
    },
    registrationProfile: {
      problemStatement: { type: String, trim: true, default: '' },
      solutionDifferentiation: { type: String, trim: true, default: '' },
      coreInnovation: { type: String, trim: true, default: '' },
      priorArtStatus: { type: String, trim: true, default: '' },
      workingMechanism: { type: String, trim: true, default: '' },
      keyComponents: { type: String, trim: true, default: '' },
      developmentStage: {
        type: String,
        enum: ['idea', 'prototype', 'mvp', 'market_ready'],
        default: 'idea',
      },
      documentationReadiness: { type: String, trim: true, default: '' },
      inventorOwnership: {
        type: String,
        enum: ['individual', 'team', 'organization'],
        default: 'individual',
      },
      developmentContext: { type: String, trim: true, default: '' },
      targetMarkets: { type: String, trim: true, default: '' },
      commercializationStrategy: {
        type: String,
        enum: ['build_startup', 'license', 'sell', 'partnership'],
        default: 'build_startup',
      },
      publicDisclosureStatus: { type: String, trim: true, default: '' },
      legalAgreements: { type: String, trim: true, default: '' },
      ipProtectionType: {
        type: String,
        enum: ['patent', 'copyright', 'trademark', 'design'],
        default: 'patent',
      },
    },
    documents: {
      type: [
        new Schema(
          {
            category: { type: String, enum: startupDocumentCategoryEnum, required: true },
            fileUrl: { type: String, required: true },
            fileType: { type: String, enum: ['pdf', 'image'], required: true },
            fileName: { type: String, required: true },
            fileSizeBytes: { type: Number, required: true },
            uploadedAt: { type: Date, default: () => new Date() },
            uploadedBy: { type: Schema.Types.ObjectId, required: true },
            note: { type: String, trim: true, default: undefined },
            cloudinaryPublicId: { type: String, default: undefined },
          },
          { _id: true },
        ),
      ],
      default: [],
    },
    launchedToInvestors: { type: Boolean, default: false },
    launchedToMentors: { type: Boolean, default: false },
    launchedToRecruiters: { type: Boolean, default: false },
    launchedAt: { type: Date, default: undefined },
    launchFormLocked: { type: Boolean, default: false },
    launchFormLockedAt: { type: Date, default: undefined },
    launchFormUnlockedByAdmin: { type: Boolean, default: false },
    launchFormUnlockedAt: { type: Date, default: undefined },
    launchFormUnlockedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    launchFormUnlockReason: { type: String, default: undefined },
    innovationScoreAtLaunch: { type: Number, default: 0 },
    totalShares: { type: Number, default: 1000, min: 1 },
    availableShares: { type: Number, default: 1000, min: 0 },
    reservedForSole: { type: Number, default: 510, min: 0 },
    maxPennyInvestors: { type: Number, default: 50, min: 1 },
    currentPennyCount: { type: Number, default: 0, min: 0 },
    hasSoleInvestor: { type: Boolean, default: false },
    soleInvestorId: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    traction: {
      patentFiled: { type: Boolean, default: false },
      mvpBuilt: { type: Boolean, default: false },
      revenueGenerating: { type: Boolean, default: false },
      usersCount: { type: Number, default: undefined },
    },
    reviewStatus: {
      type: String,
      enum: ['draft', 'review_requested', 'changes_requested', 'approved'],
      default: 'draft',
    },
    reviewRequestedAt: { type: Date, default: undefined },
    adminReviewedAt: { type: Date, default: undefined },
    adminReviewedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    adminNotes: { type: String, default: undefined },
    adminEditUnlockActive: { type: Boolean, default: false },
    adminEditUnlockApprovedAt: { type: Date, default: undefined },
    adminEditUnlockApprovedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    adminEditUnlockReason: { type: String, default: undefined },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true },
);

startupSchema.index({ teamMemberIds: 1 });
startupSchema.index({ launchedToInvestors: 1, innovationScoreAtLaunch: -1 });
startupSchema.index({ launchedToMentors: 1 });
startupSchema.index({ launchedToRecruiters: 1 });
startupSchema.index({ reviewStatus: 1, updatedAt: -1 });

export const Startup = model<IStartup>('Startup', startupSchema);
